### ISSUE TITLE
erro no trigger e na geração do report da validação local com livemark

### ISSUE THREAD

**Issue by Andrelamor** [transparencia-mg/new-dataset-template#1]

**Comment by Andrelamor** [comment]
````
(venv)
m6695506@D03GC5234264738 MINGW64 ~/Documents/CGE_transparência/repositorios/dados-mg/crimes-violentos (main)
$ livemark start
type object 'HtmlExtension' has no attribute 'parser_mixins'
(venv)
m6695506@D03GC5234264738 MINGW64 ~/Documents/CGE_transparência/repositorios/dados-mg/crimes-violentos (main)
$ make report
Gerando relatório validação html...
type object 'HtmlExtension' has no attribute 'parser_mixins'
make: *** [Makefile:22: report] Error 1

````

**Comment by gabrielbdornas** [comment]
Além do problema relatado acima, o trigger que aciona este actions não está funcionando:

https://github.com/transparencia-mg/new-dataset-template/blob/5d0a205cc5e930d6243f68594f470d867762684a/.github/workflows/local_validation.yml#L3-L7

Uma hipótese é o commit gerado pelo bot automatizado. [Nesta documentação github](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#:~:text=GitHub%20Actions.%22-,For%20example,-%2C%20a%20workflow%20with) há uma sugestão para que o trigger ocorra após outro actions rodar:

```
on:
  workflow_run:
    workflows: ["Build"]
```

Pode ser interessante até encontrarmos outra solução.

**Comment by gabrielbdornas** [comment]
> See #1
> See #4

Não funcionou. Pesquisar outra alternativa.

**Comment by gabrielbdornas** [comment]
> Além do problema relatado acima, o trigger que aciona este actions não está funcionando:
> 
> https://github.com/transparencia-mg/new-dataset-template/blob/5d0a205cc5e930d6243f68594f470d867762684a/.github/workflows/local_validation.yml#L3-L7
> 
> Uma hipótese é o commit gerado pelo bot automatizado. [Nesta documentação github](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#:~:text=GitHub%20Actions.%22-,For%20example,-%2C%20a%20workflow%20with) há uma sugestão para que o trigger ocorra após outro actions rodar:
> 
> ```
> on:
>   workflow_run:
>     workflows: ["Build"]
> ```
> 
> Pode ser interessante até encontrarmos outra solução.

Não funcionou. Pesquisar outra alternativa.

**Comment by gabrielbdornas** [comment]
@Andrelamor, encontrei [este stackoverflow](https://stackoverflow.com/questions/71695198/github-actions-does-not-get-triggered-on-commits-or-prs-created-by-github-action) perguntando porque "gitHub actions does not get triggered on commits or PRs created by github-actions (bot)".

**Comment by gabrielbdornas** [comment]
Fechado após [este commit](https://github.com/transparencia-mg/new-dataset-template/commit/7d50f1c311467eba3f395c2b1b2582adbfb01b58).
